[package]
name = "qmaur"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["QuietMisdreavus <victoria@quietmisdreavus.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
